server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.routes[0].id=payments
spring.cloud.gateway.routes[0].uri=lb://ms-books-payments
spring.cloud.gateway.routes[0].predicates[0]=Path=/payments/**
# No tocamos el path: ya existe /payments en el servicio

spring.cloud.gateway.routes[1].id=catalogue
spring.cloud.gateway.routes[1].uri=lb://ms-books-catalogue
spring.cloud.gateway.routes[1].predicates[0]=Path=/catalogue/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
